# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98a0f4798b5fc99d9f1a759ae843e595345ae7aa111f342fb3354d8d2b0b132249952bd063a672e7ffa6f39d71f39c80700fdb2d580b438695734880cd99b8f4

test:
  secret_key_base: 6b3f64a08a25d904fa5f0753474e78f9c6b6d54f2c345fd1ede57c625f932530e172d13b5c8657060db859704382a78f090d0f6965ab59abf8e9c3e69ec1d499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
